<% project_name = 'potato-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= potato_api %>_development

test:
  <<: *default
  database: <%= potato_api %>_test
